# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setMinimumSize(QtCore.QSize(0, 50))
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 50))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setMinimumSize(QtCore.QSize(0, 50))
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout.addWidget(self.settingsButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setMinimumSize(QtCore.QSize(0, 50))
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setMinimumSize(QtCore.QSize(0, 50))
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout.addWidget(self.helpButton)
        self.aboutButton = QtWidgets.QPushButton(self.centralwidget)
        self.aboutButton.setMinimumSize(QtCore.QSize(0, 50))
        self.aboutButton.setObjectName("aboutButton")
        self.horizontalLayout.addWidget(self.aboutButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabMechanism = QtWidgets.QWidget()
        self.tabMechanism.setObjectName("tabMechanism")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabMechanism)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mechanismLayout = QtWidgets.QVBoxLayout()
        self.mechanismLayout.setObjectName("mechanismLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.mechanismLayout.addItem(spacerItem2)
        self.techniqueCB = QtWidgets.QComboBox(self.tabMechanism)
        self.techniqueCB.setMinimumSize(QtCore.QSize(600, 50))
        self.techniqueCB.setObjectName("techniqueCB")
        self.techniqueCB.addItem("")
        self.techniqueCB.addItem("")
        self.mechanismLayout.addWidget(self.techniqueCB)
        self.comboMechanism = QtWidgets.QComboBox(self.tabMechanism)
        self.comboMechanism.setMinimumSize(QtCore.QSize(600, 50))
        self.comboMechanism.setObjectName("comboMechanism")
        self.comboMechanism.addItem("")
        self.comboMechanism.addItem("")
        self.comboMechanism.addItem("")
        self.comboMechanism.addItem("")
        self.mechanismLayout.addWidget(self.comboMechanism, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.invertCheckbox = QtWidgets.QCheckBox(self.tabMechanism)
        self.invertCheckbox.setObjectName("invertCheckbox")
        self.mechanismLayout.addWidget(self.invertCheckbox, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mechanismLayout.addItem(spacerItem3)
        self.mechanismImg = QtWidgets.QLabel(self.tabMechanism)
        self.mechanismImg.setObjectName("mechanismImg")
        self.mechanismLayout.addWidget(self.mechanismImg, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_2.addLayout(self.mechanismLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabMechanism, "")
        self.tabReaction = QtWidgets.QWidget()
        self.tabReaction.setObjectName("tabReaction")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabReaction)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.voltBox = QtWidgets.QGroupBox(self.tabReaction)
        self.voltBox.setObjectName("voltBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.voltBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.voltBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.Estartline = QtWidgets.QLineEdit(self.voltBox)
        self.Estartline.setObjectName("Estartline")
        self.horizontalLayout_2.addWidget(self.Estartline)
        self.label_2 = QtWidgets.QLabel(self.voltBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Eswitchline = QtWidgets.QLineEdit(self.voltBox)
        self.Eswitchline.setObjectName("Eswitchline")
        self.horizontalLayout_2.addWidget(self.Eswitchline)
        self.label_3 = QtWidgets.QLabel(self.voltBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.scanrateline = QtWidgets.QLineEdit(self.voltBox)
        self.scanrateline.setObjectName("scanrateline")
        self.horizontalLayout_2.addWidget(self.scanrateline)
        self.label_22 = QtWidgets.QLabel(self.voltBox)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.shiftEdit = QtWidgets.QLineEdit(self.voltBox)
        self.shiftEdit.setObjectName("shiftEdit")
        self.horizontalLayout_2.addWidget(self.shiftEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.voltBox)
        self.ampBox = QtWidgets.QGroupBox(self.tabReaction)
        self.ampBox.setObjectName("ampBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ampBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.ampBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.EstartAmpline = QtWidgets.QLineEdit(self.ampBox)
        self.EstartAmpline.setObjectName("EstartAmpline")
        self.horizontalLayout_3.addWidget(self.EstartAmpline)
        self.label_6 = QtWidgets.QLabel(self.ampBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.tstartline = QtWidgets.QLineEdit(self.ampBox)
        self.tstartline.setObjectName("tstartline")
        self.horizontalLayout_3.addWidget(self.tstartline)
        self.label_5 = QtWidgets.QLabel(self.ampBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.Epulseline = QtWidgets.QLineEdit(self.ampBox)
        self.Epulseline.setObjectName("Epulseline")
        self.horizontalLayout_3.addWidget(self.Epulseline)
        self.label_7 = QtWidgets.QLabel(self.ampBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.tpulseline = QtWidgets.QLineEdit(self.ampBox)
        self.tpulseline.setObjectName("tpulseline")
        self.horizontalLayout_3.addWidget(self.tpulseline)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.ampBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabReaction)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.Eformline = QtWidgets.QLineEdit(self.groupBox_3)
        self.Eformline.setObjectName("Eformline")
        self.horizontalLayout_4.addWidget(self.Eformline)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.k0line = QtWidgets.QLineEdit(self.groupBox_3)
        self.k0line.setObjectName("k0line")
        self.horizontalLayout_4.addWidget(self.k0line)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.numelline = QtWidgets.QLineEdit(self.groupBox_3)
        self.numelline.setObjectName("numelline")
        self.horizontalLayout_4.addWidget(self.numelline)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.alphaline = QtWidgets.QLineEdit(self.groupBox_3)
        self.alphaline.setObjectName("alphaline")
        self.horizontalLayout_5.addWidget(self.alphaline)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.kcfline = QtWidgets.QLineEdit(self.groupBox_3)
        self.kcfline.setObjectName("kcfline")
        self.horizontalLayout_5.addWidget(self.kcfline)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.kcrline = QtWidgets.QLineEdit(self.groupBox_3)
        self.kcrline.setObjectName("kcrline")
        self.horizontalLayout_5.addWidget(self.kcrline)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabReaction)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.concline = QtWidgets.QLineEdit(self.groupBox_4)
        self.concline.setObjectName("concline")
        self.horizontalLayout_6.addWidget(self.concline)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.diffcoefline = QtWidgets.QLineEdit(self.groupBox_4)
        self.diffcoefline.setObjectName("diffcoefline")
        self.horizontalLayout_6.addWidget(self.diffcoefline)
        self.dblabel = QtWidgets.QLabel(self.groupBox_4)
        self.dblabel.setObjectName("dblabel")
        self.horizontalLayout_6.addWidget(self.dblabel)
        self.diffcoef2line = QtWidgets.QLineEdit(self.groupBox_4)
        self.diffcoef2line.setObjectName("diffcoef2line")
        self.horizontalLayout_6.addWidget(self.diffcoef2line)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.arealine = QtWidgets.QLineEdit(self.groupBox_4)
        self.arealine.setObjectName("arealine")
        self.horizontalLayout_7.addWidget(self.arealine)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.templine = QtWidgets.QLineEdit(self.groupBox_4)
        self.templine.setObjectName("templine")
        self.horizontalLayout_7.addWidget(self.templine)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_7.addWidget(self.label_21)
        self.Cdlline = QtWidgets.QLineEdit(self.groupBox_4)
        self.Cdlline.setObjectName("Cdlline")
        self.horizontalLayout_7.addWidget(self.Cdlline)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_7.addWidget(self.label_23)
        self.ruline = QtWidgets.QLineEdit(self.groupBox_4)
        self.ruline.setObjectName("ruline")
        self.horizontalLayout_7.addWidget(self.ruline)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tabReaction, "")
        self.tabOptions = QtWidgets.QWidget()
        self.tabOptions.setObjectName("tabOptions")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabOptions)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabOptions)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.staticBt = QtWidgets.QRadioButton(self.groupBox_5)
        self.staticBt.setChecked(True)
        self.staticBt.setObjectName("staticBt")
        self.horizontalLayout_8.addWidget(self.staticBt)
        self.dynamicBt = QtWidgets.QRadioButton(self.groupBox_5)
        self.dynamicBt.setObjectName("dynamicBt")
        self.horizontalLayout_8.addWidget(self.dynamicBt)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.firstplotCB = QtWidgets.QComboBox(self.groupBox_5)
        self.firstplotCB.setObjectName("firstplotCB")
        self.firstplotCB.addItem("")
        self.firstplotCB.addItem("")
        self.firstplotCB.addItem("")
        self.firstplotCB.addItem("")
        self.horizontalLayout_9.addWidget(self.firstplotCB)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.secondplotCB = QtWidgets.QComboBox(self.groupBox_5)
        self.secondplotCB.setObjectName("secondplotCB")
        self.secondplotCB.addItem("")
        self.secondplotCB.addItem("")
        self.secondplotCB.addItem("")
        self.secondplotCB.addItem("")
        self.secondplotCB.addItem("")
        self.horizontalLayout_10.addWidget(self.secondplotCB)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        self.expFileline = QtWidgets.QLineEdit(self.groupBox_5)
        self.expFileline.setObjectName("expFileline")
        self.horizontalLayout_12.addWidget(self.expFileline)
        self.browseBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.browseBtn.setObjectName("browseBtn")
        self.horizontalLayout_12.addWidget(self.browseBtn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.blankcb = QtWidgets.QCheckBox(self.groupBox_5)
        self.blankcb.setObjectName("blankcb")
        self.horizontalLayout_11.addWidget(self.blankcb)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tabOptions, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_simEC = QtWidgets.QAction(MainWindow)
        self.actionAbout_simEC.setObjectName("actionAbout_simEC")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.runButton.setText(_translate("MainWindow", "Run simulation"))
        self.helpButton.setText(_translate("MainWindow", "Help"))
        self.aboutButton.setText(_translate("MainWindow", "About simEC"))
        self.techniqueCB.setItemText(0, _translate("MainWindow", "Voltammetry"))
        self.techniqueCB.setItemText(1, _translate("MainWindow", "Chronoamperometry"))
        self.comboMechanism.setItemText(0, _translate("MainWindow", "E"))
        self.comboMechanism.setItemText(1, _translate("MainWindow", "EC"))
        self.comboMechanism.setItemText(2, _translate("MainWindow", "CE"))
        self.comboMechanism.setItemText(3, _translate("MainWindow", "ECat"))
        self.invertCheckbox.setText(_translate("MainWindow", "Invert reaction"))
        self.mechanismImg.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/figs/E.png\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMechanism), _translate("MainWindow", "Mechanism"))
        self.voltBox.setTitle(_translate("MainWindow", "Voltammetry"))
        self.label.setText(_translate("MainWindow", "Estart"))
        self.label_2.setText(_translate("MainWindow", "Eswitch"))
        self.label_3.setText(_translate("MainWindow", "Scan rate"))
        self.label_22.setText(_translate("MainWindow", "Shift"))
        self.ampBox.setTitle(_translate("MainWindow", "Chronoamperometry"))
        self.label_4.setText(_translate("MainWindow", "Estart"))
        self.label_6.setText(_translate("MainWindow", "tstart"))
        self.label_5.setText(_translate("MainWindow", "Epulse"))
        self.label_7.setText(_translate("MainWindow", "tpulse"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Reaction"))
        self.label_8.setText(_translate("MainWindow", "Eform"))
        self.label_9.setText(_translate("MainWindow", "k0"))
        self.label_10.setText(_translate("MainWindow", "n"))
        self.label_11.setText(_translate("MainWindow", "alpha"))
        self.label_12.setText(_translate("MainWindow", "kcf"))
        self.label_13.setText(_translate("MainWindow", "kcr"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Parameters"))
        self.label_15.setText(_translate("MainWindow", "Concentration"))
        self.label_14.setText(_translate("MainWindow", "D"))
        self.dblabel.setText(_translate("MainWindow", "Db"))
        self.label_16.setText(_translate("MainWindow", "Area (cm2)"))
        self.label_17.setText(_translate("MainWindow", "T (K)"))
        self.label_21.setText(_translate("MainWindow", "Cdl (uF/cm2)"))
        self.label_23.setText(_translate("MainWindow", "Ru (Ohm)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReaction), _translate("MainWindow", "Reaction"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.staticBt.setText(_translate("MainWindow", "Static plot"))
        self.dynamicBt.setText(_translate("MainWindow", "Dynamic plot"))
        self.label_18.setText(_translate("MainWindow", "First plot"))
        self.firstplotCB.setItemText(0, _translate("MainWindow", "i vs E"))
        self.firstplotCB.setItemText(1, _translate("MainWindow", "i vs t"))
        self.firstplotCB.setItemText(2, _translate("MainWindow", "E vs t"))
        self.firstplotCB.setItemText(3, _translate("MainWindow", "E vs i"))
        self.label_19.setText(_translate("MainWindow", "Second plot"))
        self.secondplotCB.setItemText(0, _translate("MainWindow", "None"))
        self.secondplotCB.setItemText(1, _translate("MainWindow", "i vs E"))
        self.secondplotCB.setItemText(2, _translate("MainWindow", "E vs i"))
        self.secondplotCB.setItemText(3, _translate("MainWindow", "E vs t"))
        self.secondplotCB.setItemText(4, _translate("MainWindow", "i vs t"))
        self.label_20.setText(_translate("MainWindow", "Experimental data"))
        self.browseBtn.setText(_translate("MainWindow", "Browse"))
        self.blankcb.setText(_translate("MainWindow", "Overlap simulated response to blank"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOptions), _translate("MainWindow", "Options"))
        self.actionAbout_simEC.setText(_translate("MainWindow", "About simEC"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


import pics_rc
